name: Build app React
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Test app
        run: npm run test
  deploy:
    needs: test
    
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions'
          git remote set-url origin https://$ { { secrets.PAT }}@github.com/lukeku62/react-devops.git
          npx gh-pages -d dist

